// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	login: (req: LoginRequest) => typedError<SessionInfo, CoreError>(__TAURI_INVOKE("login", { req })),
	restoreSession: () => typedError<{
	user: User,
	device_id: DeviceId,
} | null, CoreError>(__TAURI_INVOKE("restore_session")),
	logout: () => typedError<null, CoreError>(__TAURI_INVOKE("logout")),
	listSpaces: () => typedError<Space[], CoreError>(__TAURI_INVOKE("list_spaces")),
	listRooms: () => typedError<Room[], CoreError>(__TAURI_INVOKE("list_rooms")),
	getMembers: (room: RoomId) => typedError<Member[], CoreError>(__TAURI_INVOKE("get_members", { room })),
	loadTimeline: (room: RoomId, limit: number) => typedError<TimelineChunk, CoreError>(__TAURI_INVOKE("load_timeline", { room, limit })),
	loadOlder: (room: RoomId, before: MessageId, limit: number) => typedError<TimelineChunk, CoreError>(__TAURI_INVOKE("load_older", { room, before, limit })),
	sendMessage: (room: RoomId, content: OutgoingContent) => typedError<MessageId, CoreError>(__TAURI_INVOKE("send_message", { room, content })),
	editMessage: (room: RoomId, target: MessageId, content: OutgoingContent) => typedError<null, CoreError>(__TAURI_INVOKE("edit_message", { room, target, content })),
	redactMessage: (room: RoomId, target: MessageId) => typedError<null, CoreError>(__TAURI_INVOKE("redact_message", { room, target })),
	toggleReaction: (room: RoomId, target: MessageId, key: string) => typedError<null, CoreError>(__TAURI_INVOKE("toggle_reaction", { room, target, key })),
	markRead: (room: RoomId, upTo: MessageId) => typedError<null, CoreError>(__TAURI_INVOKE("mark_read", { room, upTo })),
	setTyping: (room: RoomId, typing: boolean) => typedError<null, CoreError>(__TAURI_INVOKE("set_typing", { room, typing })),
	uploadMedia: (path: string) => typedError<MediaRef, CoreError>(__TAURI_INVOKE("upload_media", { path })),
	requestVerification: (user: UserId) => typedError<null, CoreError>(__TAURI_INVOKE("request_verification", { user })),
	confirmSas: (flow: string) => typedError<null, CoreError>(__TAURI_INVOKE("confirm_sas", { flow })),
	cancelVerification: (flow: string) => typedError<null, CoreError>(__TAURI_INVOKE("cancel_verification", { flow })),
};

/** Events */
export const events = {
	coreEventMsg: makeEvent<CoreEventMsg>("core-event-msg"),
};

/* Types */
/**
 *  Canonical error surface handed to the UI. Categories are actionable; internal
 *  detail is logged inside the core and never leaked through `Internal`.
 */
export type CoreError = { type: "Auth"; message: string } | { type: "Network" } | { type: "NotFound" } | { type: "Forbidden" } | { type: "RateLimited"; retry_after_ms: number | null } | { type: "Encryption"; message: string } | { type: "Internal" };

/**
 *  Reactive updates pushed from the core to the UI. The Tauri layer forwards
 *  each of these to the webview as an event.
 */
export type CoreEvent = { type: "Session"; state: SessionState } | { type: "Sync"; state: SyncState } | { type: "RoomUpserted"; room: Room } | { type: "RoomRemoved"; room: RoomId } | { type: "SpaceUpserted"; space: Space } | { type: "Timeline"; room: RoomId; change: TimelineChange } | { type: "Typing"; room: RoomId; users: UserId[] } | { type: "Receipt"; room: RoomId; user: UserId; up_to: MessageId } | { type: "Presence"; user: User } | { type: "Verification"; update: VerificationUpdate };

/**
 *  Wrapper so the core's `CoreEvent` can be a typed tauri-specta event without
 *  the core depending on Tauri. The frontend reads `payload.event`.
 */
export type CoreEventMsg = {
	event: CoreEvent,
};

export type DeviceId = string;

export type EncryptionState = "Unencrypted" | "Encrypted" | 
/**  Encrypted, but unverified devices are present (show a shield warning). */
"EncryptedUnverified";

export type LoginRequest = {
	homeserver: string,
	username: string,
	/**
	 *  Crosses the boundary once, into the core. The core persists the session,
	 *  never the password. OIDC/SSO (where the password never touches our code)
	 *  is the more secure path to add later.
	 */
	password: string,
};

/**
 *  Opaque handle. The UI never fetches from the homeserver and never holds media
 *  keys: it renders via a custom protocol the Rust side serves (for example
 *  `vauxl-media://{id}`), where the core fetches the ciphertext, decrypts in
 *  Rust, and streams plaintext bytes to the webview.
 */
export type MediaRef = {
	id: string,
	thumbnail: string | null,
};

export type Member = {
	user: User,
	membership: Membership,
	/**  Canonical permission weight (a Matrix power level maps in here). */
	power_level: number,
	roles: string[],
};

export type Membership = "Joined" | "Invited" | "Left" | "Banned";

export type Message = {
	id: MessageId,
	room: RoomId,
	sender: UserId,
	timestamp: number | null,
	content: MessageContent,
	reactions: Reaction[],
	reply_to: MessageId | null,
	edited: boolean,
	send_state: SendState,
	sender_trust: SenderTrust,
};

export type MessageContent = { type: "Text"; body: string; formatted: SafeHtml | null } | { type: "Image"; media: MediaRef; alt: string | null; blurhash: string | null; width: number; height: number } | { type: "File"; media: MediaRef; filename: string; size: number | null; mime: string } | { type: "Audio"; media: MediaRef; duration_ms: number } | { type: "Redacted" } | 
/**  Graceful fallback for unknown or extension content. */
{ type: "Unsupported"; kind: string };

export type MessageId = string;

export type MessagePreview = {
	sender_name: string,
	snippet: string,
	timestamp: number | null,
};

export type OutgoingContent = { type: "Text"; body: string; formatted: string | null; reply_to: MessageId | null } | { type: "Media"; upload: MediaRef; caption: string | null };

export type Presence = "Online" | "Idle" | "DoNotDisturb" | "Offline";

export type Reaction = {
	key: string,
	count: number,
	me: boolean,
};

export type Room = {
	id: RoomId,
	space: SpaceId | null,
	kind: RoomKind,
	name: string,
	topic: string | null,
	avatar: MediaRef | null,
	unread: UnreadInfo,
	encryption: EncryptionState,
	member_count: number,
	last_message: MessagePreview | null,
};

export type RoomId = string;

export type RoomKind = "Text" | "Voice" | "Announcement" | "DirectMessage";

/**
 *  HTML the core only constructs after sanitizing (for example with `ammonia`).
 *  The UI can render it without re-sanitizing. Raw HTML never crosses the boundary.
 */
export type SafeHtml = string;

export type SasEmoji = {
	symbol: string,
	name: string,
};

export type SendState = 
/**  Optimistic local echo, not yet acknowledged. */
{ type: "Local" } | { type: "Sending" } | { type: "Sent" } | { type: "Failed"; reason: string };

export type SenderTrust = "Verified" | "Unverified" | "Unknown";

export type SessionInfo = {
	user: User,
	device_id: DeviceId,
};

export type SessionState = { type: "LoggedOut" } | { type: "Authenticating" } | { type: "Recovering" } | { type: "Ready"; user: User } | { type: "Error"; message: string };

export type Space = {
	id: SpaceId,
	name: string,
	avatar: MediaRef | null,
	rooms: RoomId[],
	order: number,
};

export type SpaceId = string;

export type SyncState = { type: "Offline" } | { type: "Connecting" } | { type: "Syncing" } | { type: "Live" } | { type: "Error"; message: string };

export type TimelineChange = { op: "Added"; message: Message } | { op: "Updated"; message: Message } | { op: "Removed"; id: MessageId };

export type TimelineChunk = {
	messages: Message[],
	reached_start: boolean,
};

export type UnreadInfo = {
	unread: number,
	highlights: number,
	muted: boolean,
};

export type User = {
	id: UserId,
	display_name: string,
	avatar: MediaRef | null,
	presence: Presence,
	status_message: string | null,
};

export type UserId = string;

export type VerificationUpdate = { type: "Requested"; from: UserId; flow: string } | { type: "ShowSas"; flow: string; emoji: SasEmoji[] } | { type: "Done"; flow: string } | { type: "Cancelled"; flow: string; reason: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

